### ISSUE TITLE
Fatal Error on user registration when plugin is active

### ISSUE THREAD

**Issue by BoweFrankema** [WeFoster/bp-feeds#15]
When a user registers the following fatal error occurs

"Fatal error: Cannot use object of type WP_User as array in /Users/Bowromir/webserver/cfcommunity.net/wp-content/plugins/buddypress-rss-feeds/core/front_members.php on line 222"

**Comment by BoweFrankema** [comment]
Ok this started happening again. You can reproduce this by going here:

http://cfcommunity.net/become-a-member/

And filling in the registration form. It will give the fatal error after registration.

"Fatal error: Cannot use object of type WP_User as array in /srv/users/serverpilot/apps/cfcommunity/public/wp-content/plugins/buddypress-rss-feeds/core/front_members.php on line 227"

The reason I could not reproduce this before is because I was registering my account through a subsite in the network and BuddyPress RSS Feeds was not active there.

**Comment by slaFFik** [comment]
@BoweFrankema 
I can't replicate. Can you please test this one more time and provide some feedback?
That error message is not valid any more, on that line another code is currently located.

**Comment by BoweFrankema** [comment]
Let me pull in the latest changes again
